### ISSUE TITLE
Sega Chihiro Games Support

### ISSUE THREAD

**Issue by chris12023** [teknogods/TeknoParrot#13]
Support For Sega Chihiro Games
1. Wangan Midnight Maximum Tune
2. Wangan Midnight Maximum Tune 2
3. OutRun 2
4. OutRun 2 SP
5. Ghost Squad
6. Virtua Cop 3
7. Crazy Taxi High Roller
8. Ollie King
9. The House of the Dead III
10. Kidou Senshi Gundam: Battle Operating Simulator
11. And All Sega Chihiro Satellite Terminal Games

**Comment by Boomslangnz** [comment]
Please don’t spam multiple issues everywhere. Make 1 post with issues you have. This is not the place to ask for game support

**Comment by ThatOneGuyFromThatShow** [comment]
Outrun 2 is already emulated by Teknoparrot. In the test menu you can set it to the regular Outrun 2 Sp.

**Comment by nzgamer41** [comment]
schizo man chris (not you ThatOneGuyFromThatShow) fails to understand the SEGA Chihiro is NOT A PC BASED PLATFORM, and is based off the original Xbox. Ask in the xemu github.
