### ISSUE TITLE
Outrun 2 SP SDX 

### ISSUE THREAD

**Issue by GodLikeHeadShot** [teknogods/TeknoParrot#24]
When you complete Outrun the end credits black screen appears. The end credits scroll on the right hand side, as they should but all the end videos/clips are missing from the left hand side. I have tried different Outrun 2 SP ROMs, and all have the same issue. It does work fine on older version of TeknoParrot though. I tried v1.0.0.140 and it worked OK.

**Comment by GodLikeHeadShot** [comment]
When you complete Outrun the end credits black screen appears. The end credits scroll on the right hand side, as they should but all the end videos/clips are missing from the left hand side. I have tried different Outrun 2 SP ROMs, and all have the same issue. It does work fine on older version of TeknoParrot though. I tried v1.0.0.140 and it worked OK.

**Comment by dronrvgl** [comment]
The videos work at 800x480 resolution. At a higher resolution, the screen is black.

**Comment by Boomslangnz** [comment]
yeah need to run at normal vga res
