### ISSUE TITLE
Fullscreen setting causes parts of game to run slowly in IDZv2TP

### ISSUE THREAD

**Issue by bagelswitch** [teknogods/TeknoParrot#27]
With current TeknoParrot core (1.0.0.937), something is wrong w/ the game speed when TP fullscreen setting is used in IDZv2TP profile - the UI and timers run normally, but the vehicles move at only half-speed or slower (visually/physically, although indicated kph is normal), making it impossible to reach checkpoints in time . . . windowed and fullscreen-windowed modes don't show the problem and work great.

**Comment by bagelswitch** [comment]
Confirmed that this is happening because in CEA 4k resolution, the first available mode enumerated for the monitor by windows has a 30Hz refresh - problem goes away if using a different monitor, or resolution that has a mode with 60Hz refresh listed first.

**Comment by Johno362** [comment]
I have 60hz tv and I still have the same issue
