### ISSUE TITLE
Teknoparrot Add More Games

### ISSUE THREAD

**Issue by chris12012** [teknogods/TeknoParrot#30]
Excuse Me In The Next Update of Teknoparrot Will You Add More Games For Example Wangan Midnight Maximum Tune 3DX 3DX+ & 4 & 6RR & Initial D Arcade Stage Zero Version 2.30 & Maximum Heat 3D MAX & Guilty Gear Xrd Revelator & BlazBlue Chronophantasma & BlazBlue Chronophantasma 2.0 & BlazBlue Continuum Shift Extend

**Comment by MediaProductions** [comment]
![safsagsagagfdhgf](https://user-images.githubusercontent.com/65030380/228939964-58f8268c-fa9e-41a2-994d-53a239d08253.PNG)
the 6rr xml is from me
also you staret v2.30 over initial D Arcade stage zer0 V2 the first is with segatools the second without segatools so you don't need to add v2.30 it's already there watching tutorials would help you .
