### ISSUE TITLE
Mario Kart GP DX Banapass Problem

### ISSUE THREAD

**Issue by DrGlaxer** [teknogods/TeknoParrot#31]
TeknoParrot version: 1.0.0.971
Game with issue: Mario Kart GP DX 1.10 & 1.18
Detailed description of issue: Created a new ID, entered the game, appeared online at first however it then disconnect once use banapass. Cannot connect to Banapass, cant save.
Any other details: Allowed firewall for the following game public and private/
Pictures of issue:
![IMG_3288](https://user-images.githubusercontent.com/129174317/228225935-937e02f7-3f88-4fcc-8bc0-56a93600a030.jpg)
![IMG_3293](https://user-images.githubusercontent.com/129174317/228225951-48e6ec08-f6a6-437f-a457-708652c802b8.jpg)
![IMG_3295](https://user-images.githubusercontent.com/129174317/228225962-78aa862e-f5ae-4e21-8945-064422901ca4.jpg)

https://user-images.githubusercontent.com/129174317/228225965-91c78f43-dc6b-44ba-8916-d585732ccccb.mov

![IMG_3303](https://user-images.githubusercontent.com/129174317/228225970-42d48b52-7d2c-4634-84c8-b3deae303896.jpg)

**Comment by emuline** [comment]
The problem is known, here is the true problem :

- old Mario kart ID can connect with sucess and load their banapass profile
- New brand ID cannot, they have Green server but when they use F2 to load banapass card, they are disconnected

there was a similar bug a few months ago..
