### ISSUE TITLE
After Burner crash on start

### ISSUE THREAD

**Issue by Ataru09** [teknogods/TeknoParrot#44]
After Burner Climax hangs at the system startup screen and returns to the Teknoparrot main menu . I use an I7 7735hs mini PC, with integrated AMD 680 GPU. Could it be an integrated GPU problem?

**Comment by Nezarn** [comment]
Use older drivers (like 22.5.1), newer fix will come when its done.

duplicate issue https://github.com/teknogods/TeknoParrotUI/issues/518
