### ISSUE TITLE
Ghost Squad Evolution (elfloader2) - No background music after Teknoparrot update sent out on 10.10.24

### ISSUE THREAD

**Issue by Bluerage2k** [teknogods/TeknoParrot#61]
My System:
AMD Ryzen T
![Ghost Squad Evolution white screen when movie should be playing ](https://github.com/user-attachments/assets/a48fd452-95ff-4399-951c-5021ec7ec3a4)
![Ghost Squad Evolution white screen when movie should be playing ](https://github.com/user-attachments/assets/0ae5f623-ba7c-4551-8629-062903c90902)
hreadripper 1950X 16-Core Processor    3.40 GHz
64.0 GB system ram
Nvidia 2080TI
Windows 10 Pro

Issue:
After the Teknoparrot update on the 10.10.24, Ghost Squad Evolution (elfloader 2) plays all the sounds like gunshots, charater sounds etc , howver there is no music at all this effects all menus and even intermission scenes before you start a game. The initial short movie that plays at the beginning after explaining how to play the game only shows a white screen with start button message (see screenshot). Please note everything was working perfectly before this specific updated. (luckily, i test my favourite games after every update).  Thanks

**Comment by bro007-eng** [comment]
Agree same issue a few have reported this now :( version of TP 1392 no issues.

**Comment by bro007-eng** [comment]
Latest update seems to have resolved this issue for me - thank you.
