### ISSUE TITLE
Games With Controller Issues

### ISSUE THREAD

**Issue by OndaCouch421** [teknogods/TeknoParrot#8]
Lets Go Safari-Can’t Steer
Batman-U turn doesn’t work 
Guitar Hero Arcade-can’t press start to continue when the song ends
Gaelco Championship Tuning Race-steering is incorrect its impossible to control the car correctly during the race
Cars 2-no drift using xinput 
Star Wars battle pod-brakes don’t work properly most of the time

**Comment by ThanosAtha** [comment]
Does it support generic usb gamepads, (or keyboard arrows for player 2 LightGun)  ???

edit: a bit usefull is TeamPlayer 2.0
